services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mariadb:10.11
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=refactorian
      - MYSQL_USER=refactorian
      - MYSQL_PASSWORD=refactorian
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8080:80
    links:
        - db
    environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
    volumes:
        - ./docker/phpmyadmin/sessions:/sessions
  adminer:
    image: adminer
    ports:
        - 9090:8080
    depends_on:
      - db
